export const environment = {
    production: false,
    // Remote app URLs for portal switching
    remotes: {
        dealer: 'http://localhost:4201',
        commercial: 'http://localhost:4202',
        admin: 'http://localhost:4203',
    },
    microservices: {
        contractCommercial: 'ContractCommercial',
        assetCommercial: 'AssetCommercial',
        paymentCommercial: 'PaymentCommercial',
        UserCommercial: 'UserCommercial',
        ReportCommercial: 'ReportCommercial',
        LookupCommercial: 'LookupCommercial',
        ServicingRequest: 'ServicingRequest',
        CommercialDocument: 'CommercialDocument',
        TaskCommercial: 'TaskDetails',
        Product: 'Product',
        NoteCommercial: 'NoteCommercial',
        Contract: 'Contract',
        Motocheck: 'Motocheck',
        customerCommercial: 'CustomerDetailsCommercial',
        WorkFlowsCommercial: 'WorkFlowsCommercial',
        DocumentService: 'DocumentServices',
    },
    // apiUrl: 'https://portalgateway/gateway',
    // apiUrl: 'https://portalgatewaydev:447/gateway',
    //  apiUrl: 'https://udcdevportalgateway:444/gateway',
    apiUrl: 'http://testudcportalgateway:444/gateway',
    // OIDC Config : Start
    authority:
        'https://login.microsoftonline.com/2c4787bf-22ff-4192-bda2-7055d259e141',
    revokeAllTokenFIS:
        'https://login10.fisglobal.com/idp/aurionpro/rest/1.0/idptoken/delete/alltoken/me',
    redirectUrl: window.location.origin + '/authentication',
    postLogoutRedirectUri: window.location.origin + '/post-logout',
    CommonConfiguration: "/auro-ui-assets/api-json/commonConfiguration.json",
    // clientId: 'd4ea1b2b-7183-4465-a51a-d36e7f10ca69',

    scope: 'openid profile email User.Read',
    autoUserInfo: false,
    responseType: 'code',
    silentRenew: true,
    useRefreshToken: true,
    secureRoutes: ['https://graph.microsoft.com/'],
    maxIdTokenIatOffsetAllowedInSeconds: 600,
    FIS: true,
    grant_type: 'client_credentials',
};
